In [2]:
import numpy as np

def calcular_coeficiente_de_peligro(tablero, jugador):
    # Asumiendo que tablero es una matriz de NxN donde:
    # 0 representa una casilla vacía
    # 1 representa una ficha del jugador 1
    # 2 representa una ficha del jugador 2
    
    n = len(tablero)
    coeficiente_de_peligro = np.zeros((n, n))
    
    # Define los coeficientes
    coef_amigo = 1  # Coeficiente para una ficha amiga
    coef_enemigo = -1  # Coeficiente para una ficha enemiga
    
    # Asigna el coeficiente de acuerdo al jugador
    if jugador == 1:
        amigo = 1
        enemigo = 2
    else:
        amigo = 2
        enemigo = 1
    
    # Función auxiliar para calcular el coeficiente de una casilla
    def coeficiente_casilla(x, y):
        coef = 0
        # Coordenadas de los movimientos posibles (arriba, abajo, izquierda, derecha)
        movimientos = [(-1, 0), (1, 0), (0, -1), (0, 1)]
        for dx, dy in movimientos:
            nx, ny = x + dx, y + dy
            if 0 <= nx < n and 0 <= ny < n:  # Verifica que las coordenadas estén dentro del tablero
                if tablero[nx][ny] == amigo:
                    coef += coef_amigo
                elif tablero[nx][ny] == enemigo:
                    coef += coef_enemigo
        return coef
    
    # Calcula el coeficiente de peligro para cada casilla del tablero
    for i in range(n):
        for j in range(n):
            coeficiente_de_peligro[i][j] = coeficiente_casilla(i, j)
    
    # Normaliza los coeficientes a un rango de -4 a +4
    coeficiente_de_peligro = np.clip(coeficiente_de_peligro, -4, 4)
    
    return coeficiente_de_peligro

# Ejemplo de uso
tablero = [
    [0, 1, 0, 0],
    [2, 0, 0, 0],
    [0, 2, 1, 0],
    [2, 0, 0, 2]
]

jugador = 1
coef_peligro = calcular_coeficiente_de_peligro(tablero, jugador)
print(coef_peligro)


[[ 0.  0.  1.  0.]
 [ 0. -1.  1.  0.]
 [-3.  1. -1.  0.]
 [ 0. -2.  0.  0.]]


In [3]:
import numpy as np

def calcular_coeficiente_de_peligro(tablero, jugador):
    # Asumiendo que tablero es una matriz de NxN donde:
    # 0 representa una casilla vacía
    # 1 representa una ficha del jugador 1
    # 2 representa una ficha del jugador 2
    
    n = len(tablero)
    coeficiente_de_peligro = np.zeros((n, n), dtype=object)
    
    # Define los coeficientes
    coef_amigo = 1  # Coeficiente para una ficha amiga
    coef_enemigo = -1  # Coeficiente para una ficha enemiga
    
    # Asigna el coeficiente de acuerdo al jugador
    if jugador == 1:
        amigo = 1
        enemigo = 2
    else:
        amigo = 2
        enemigo = 1
    
    # Función auxiliar para calcular el coeficiente de una casilla
    def coeficiente_casilla(x, y):
        coef = 0
        # Coordenadas de los movimientos posibles (arriba, abajo, izquierda, derecha)
        movimientos = [(-1, 0), (1, 0), (0, -1), (0, 1)]
        for dx, dy in movimientos:
            nx, ny = x + dx, y + dy
            if 0 <= nx < n and 0 <= ny < n:  # Verifica que las coordenadas estén dentro del tablero
                if tablero[nx][ny] == amigo:
                    coef += coef_amigo
                elif tablero[nx][ny] == enemigo:
                    coef += coef_enemigo
        return coef
    
    # Calcula el coeficiente de peligro para cada casilla del tablero
    for i in range(n):
        for j in range(n):
            if tablero[i][j] == 1:
                coeficiente_de_peligro[i][j] = 'O'
            elif tablero[i][j] == 2:
                coeficiente_de_peligro[i][j] = 'X'
            else:
                coeficiente_de_peligro[i][j] = coeficiente_casilla(i, j)
    
    # Normaliza los coeficientes a un rango de -4 a +4 para casillas vacías
    for i in range(n):
        for j in range(n):
            if isinstance(coeficiente_de_peligro[i][j], (int, float)):
                coeficiente_de_peligro[i][j] = np.clip(coeficiente_de_peligro[i][j], -4, 4)
    
    return coeficiente_de_peligro

# Ejemplo de uso
tablero = [
    [0, 1, 0, 0],
    [2, 0, 0, 0],
    [0, 2, 1, 0],
    [2, 0, 0, 2]
]

jugador = 1
coef_peligro = calcular_coeficiente_de_peligro(tablero, jugador)
print(coef_peligro)


[[0 'O' 1 0]
 ['X' -1 1 0]
 [-3 'X' 'O' 0]
 ['X' -2 0 'X']]


In [4]:
jugador = 2
coef_peligro = calcular_coeficiente_de_peligro(tablero, jugador)
print(coef_peligro)

[[0 'O' -1 0]
 ['X' 1 -1 0]
 [3 'X' 'O' 0]
 ['X' 2 0 'X']]
